"""Removing the init=False constrain in the relationship between Cards, Words and PRompts

Revision ID: de6849586f6c
Revises: 853e0aac48e5
Create Date: 2025-03-31 19:01:41.746293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de6849586f6c'
down_revision: Union[str, None] = '853e0aac48e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
